name: pathagar
version: git
summary: Pathagar Book Server
description: >-
  Pathagar is a digital book server used to serve content in classrooms and
  community over a local offline network.

base: core18
grade: devel
confinement: devmode

parts:
  pathagar:
    plugin: python
    python-version: python2
    source: https://github.com/PathagarBooks/pathagar.git
    source-type: git
    requirements: requirements.txt
    build-packages:
      - libxml2-dev
      - libxslt-dev
    # TODO add a setup.py so that the python plugin can call python setup.py
    # bdist_wheel and install pathagar to the python lib directory. Then we
    # can use django-admin to run the application from anywhere without having to
    # copy files around and making sure we're running manage.py from the right
    # directory.
    install: |-
      mkdir $SNAPCRAFT_PART_INSTALL/app
      cp -R . $SNAPCRAFT_PART_INSTALL/app/

  # This step copies any additional files not part of pathagar that we need
  # for the snap.
  local:
    plugin: nil
    source: .
    override-build: |
      install -m 0755 -d $SNAPCRAFT_PART_INSTALL/usr/bin
      install -m 0755 bin/pathagar.sh $SNAPCRAFT_PART_INSTALL/usr/bin


apps:
  start:
    command: pathagar.sh
    plugs:
      - network
      - network-bind
  manage:
    command: python $SNAP/app/manage.py
    plugs:
      - network
