name: pathagar
version: git
summary: Pathagar Book Server
description: >-
  Pathagar is a digital book server used to serve content in classrooms and
  community over a local offline network.

base: core18
confinement: devmode

parts:
  pathagar:
    plugin: python
    python-version: python2
    source: https://github.com/PathagarBooks/pathagar.git
    source-type: git
    requirements: requirements.txt
    build-packages:
      - libxml2-dev
      - libxslt-dev

apps:
  pathagar:
    command: |-
      python manage.py migrate
      python manage.py runserver
